### ISSUE TITLE
后台输出无法通过MiraiMC配置禁用

### ISSUE THREAD

**Issue by TUCAOEVER** [DreamVoid/MiraiMCAddon-Overflow#2]
```
bot:
  disable-network-logs: true
  disable-bot-logs: true
```
配置文件中两个选项已设置为禁用 后台仍会输出两条日志信息
  
![QQ_1723599172525](https://github.com/user-attachments/assets/42070bd4-a0ba-46c8-92f0-b71737e0e52f)

**Comment by DreamVoid** [comment]
配置文件在构建mirai机器人时才会使用，构建overflow机器人的时候我没找到调配置的方法，所以目前无法避免
至于第二条日志，你应该关闭 `general.log-event`

**Comment by TUCAOEVER** [comment]
> 配置文件在构建mirai机器人时才会使用，构建overflow机器人的时候我没找到调配置的方法，所以目前无法避免
> 至于第二条日志，你应该关闭 `general.log-event`

已向Overflow作者反馈并添加Bot Configuration
