### ISSUE TITLE
overflow-core的2.16.0-e2ed65e-SNAPSHOT是否已经失效？

### ISSUE THREAD

**Issue by jbji** [DreamVoid/MiraiMCAddon-Overflow#5]
https://github.com/DreamVoid/MiraiMCAddon-Overflow/blob/877afedae1ac916d413e5e0c7da48de59fcd678d/src/main/java/me/dreamvoid/miraimcaddon/overflow/BukkitPlugin.java#L23

加载Release中的插件时此行会报错提示相应库不存在从而加载失败，简单替换为
```java
loader.loadLibraryMaven("top.mrxiaom.mirai", "overflow-core-all", System.getProperty("MiraiMC.overflow-version", "1.0.0.533-7d6c17e-SNAPSHOT"), "https://s01.oss.sonatype.org/content/repositories/snapshots", "-all.jar", dataDirectory);
```
重新编译后插件可以使用。

**Comment by DreamVoid** [comment]
原来我没改bukkit的代码啊
